### ISSUE TITLE
Images of espanish interface

### ISSUE THREAD

**Issue by Cusiri1971** [semiautomaticgit/SemiAutomaticClassificationManual_v5#1]
Hi Luca,
My problem is that 'I can't stop'.
There is a link to images with Spanish interface.
 https://dl.dropboxusercontent.com/u/19424912/_static_es.tar.7z

in my tests, with what little I've learned about sphinx, the images are arranged in an acceptable manner. I have problems with Cyrillic characters, and sections that do not appear numbered.

Regards.

**Comment by semiautomaticgit** [comment]
Hi Igor,
wow, that's impressive. Thank you very much.
I'll try to add these images to the manual.

Regards

**Comment by semiautomaticgit** [comment]
Hi Igor,
you can see your excellent work here
http://semiautomaticclassificationmanual-v5.readthedocs.io/es/latest/main_interface_window.html
It looks very good. Thank you!

**Comment by Cusiri1971** [comment]
Thanks you too. Yes, it looks very good. :smiley:  :boom:
